# Generated by Django 5.0.6 on 2024-07-08 13:54

import apps.aiauth.models
import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'ai_department',
            },
        ),
        migrations.CreateModel(
            name='AIUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('is_staff', models.BooleanField(default=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Unactive'), (3, 'Locked')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', related_query_name='staffs', to='aiauth.aidepartment')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='aiuser_set', related_query_name='aiuser', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='aiuser_set', related_query_name='aiuser', to='auth.permission')),
            ],
            options={
                'db_table': 'ai_users',
            },
            managers=[
                ('objects', apps.aiauth.models.AIUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='aidepartment',
            name='leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_department', related_query_name='leader_department', to='aiauth.aiuser'),
        ),
        migrations.AddField(
            model_name='aidepartment',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_department', related_query_name='manager_department', to='aiauth.aiuser'),
        ),
    ]
